name: flutter_audiostream
version: 0.0.2
description: A flutter plugin to play audio files
author: Erick Ghaumez <contact@rxlabz.com>

flutter:
  plugin:
    androidPackage: bz.rxla.flutter_audiostream
    pluginClass: FlutterAudiostreamPlugin

dependencies:
  flutter:
    sdk: flutter
